version: '3.8'

services:
  java:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"     # Mapea el puerto 8080 del contenedor al host
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://13.222.227.191:3306/db_agenda
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpass
    command: ["java", "-jar", "app.jar"]
