version: '3.8'

services:
  java:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8081:8081"     # Mapea el puerto 8081 del contenedor al host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://13.222.227.191:3306/db_agenda
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: adminpass
    command: ["java", "-jar", "app.jar"]
